# from the three dog night song: "Joy to the World, Jeremiah was a bullfrog"
puts "Joy to the world"
puts "All the boys and girls"
# puts "Joy to the fishes in the deep blue sea"
puts "Joy to you and me"